### ISSUE TITLE
✨ Question: How to hide the line break signs?

### ISSUE THREAD

**Issue by merlinuwe** [ebullient/obsidian-show-whitespace-cm6#148]
### 🔖 Feature description

Thanks for your great plugin. 

How can I hide the character for the line break at the end of the line and between paragraphs?

![image](https://github.com/user-attachments/assets/38c6bbfb-ca2f-49b9-8686-25d80447857c)

### ✔️ Solution

-

### ❓ Alternatives

-

### 📝 Additional Context

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: dark
	Community theme: MagicUser v20.8.0
	Snippets enabled: 43
	Restricted mode: off
	Plugins installed: 161
	Plugins enabled: 67

**Comment by merlinuwe** [comment]
I tried a little bit with your styles.css. 
How can I supress the line breaks and the single spaces?
How can I color the double spaces?

**Comment by ebullient** [comment]
Make sure you've updated the plugin and have checked settings and what they do (toggle them on and off, if you have an editor open in the background, you should see the changes).

I've just updated, and will shortly release, a small modification to styles. Your snippet should be able to redefine the following:

```css
body {
  --line-end: '¬';
  --line-break: '↲';
}
```

If you want to remove the line endings, change that to an empty value (`''`)

**Comment by merlinuwe** [comment]
Thanks for the new release and this code snippet, but the code snippet with empty values ('') seems to slow down considerately editing in Obsidian.

**Comment by ebullient** [comment]
This plugin always shows leading whitespace.

For most indentation, it's index of 4 (that's how CodeMirror works, and I'm for the most part using the data values they define). 

No leading indent is required for lists in YAML headers, get rid of that by removing it.

```yaml
tags:
- tag
```

**Comment by merlinuwe** [comment]
For me, this seems to be the solution:

```css
/* Verhindere Formatierung in Markdown-Tabellen */
.cm-line:not(.HyperMD-table-row) {
    --line-end: none;
    --line-break: none;
    white-space: normal;
    overflow-wrap: break-word;
    word-wrap: break-word;
    hyphens: auto;
}

/* Leerzeichen - nicht in Tabellen anwenden */
.cm-line:not(.HyperMD-table-row) .cm-highlightSpace[data-display="·"],
.cm-line:not(.HyperMD-table-row) .cm-hmd-internal-link .cm-highlightSpace[data-display="·"] {
    background-color: transparent !important;
}

.cm-line:not(.HyperMD-table-row) .cm-highlightSpace[data-display="··"]:not(:first-child) {
    background-color: rgba(255, 0, 0, 0.3);
}

.cm-line:not(.HyperMD-table-row) .cm-highlightSpace[data-display="···"]:not(:first-child),
.cm-line:not(.HyperMD-table-row) .cm-highlightSpace[data-display="····"]:not(:first-child),
.cm-line:not(.HyperMD-table-row) .cm-highlightSpace[data-display^="····"]:not(:first-child) {
    background-color: rgba(255, 0, 0, 0.3) !important;
}

/* Interne Links und Klammern - nicht in Tabellen anwenden */
.cm-line:not(.HyperMD-table-row) .cm-hmd-internal-link {
    text-decoration: none;
    border-bottom: 1px solid #00A9DD;
}

.cm-line:not(.HyperMD-table-row) .cm-hmd-internal-link .cm-highlightSpace[data-display^="··"] {
    background-color: rgba(255, 0, 0, 0.3) !important;
    border-radius: 5px;
}

/* Klammernpaare um wiki-Links */
/*
.cm-line:not(.HyperMD-table-row) .cm-formatting-link {
    background-color: rgba(0, 128, 255, 0.3);
}
*/
```
(You can use this as an example or use it in any way.)

Thanks a lot for your help.
