### ISSUE TITLE
🐛 On lines without content, visual line breaks (¬) have volume.

### ISSUE THREAD

**Issue by jerrychan7** [ebullient/obsidian-show-whitespace-cm6#235]
### Expected Behavior

Visual line breaks (¬) should not take up input space, regardless of whether there is content in the line or not.

### Current behaviour

On lines without content, visual line breaks (¬) take up one character position.
But on lines with content, visual line breaks (¬) do not take up a position.

### Steps to reproduce

![image](https://github.com/user-attachments/assets/5e69cbf3-edb7-473c-aa97-30ff4612199a)

![image](https://github.com/user-attachments/assets/af09c856-63b2-4210-95f1-74a4de505f06)

### Which Operating Systems are you using?

- [X] Android
- [ ] iPhone/iPad
- [ ] Linux
- [x] macOS
- [X] Windows

### Obsidian Version

1.7.7

### Plugin Version

0.2.6

### Checks

- [X] I have tried it in the sandbox vault with only this plugin enabled

### Possible solution

```css
body:not(.swcm6-nix-plugin-styles) .markdown-source-view.mod-cm6 .cm-line:has(br):not(:has(span)):before {
  display: inline-block;
  width: 0;
}
```
